services:
  - type: web
    name: attendancems
    env: php
    rootDir: AttendanceMS-Server
    buildCommand: |
      composer install --no-interaction --prefer-dist --optimize-autoloader
      php artisan key:generate
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
